# Generated by Django 6.0 on 2025-12-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_availability_id_alter_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
