# Generated by Django 6.0 on 2025-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_studentprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
