# Generated by Django 6.0 on 2025-12-20 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_studentprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 0 or + and contain digits only.', regex='^(0|\\+)\\d+$')]),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 0 or + and contain digits only.', regex='^(0|\\+)\\d+$')]),
        ),
    ]
