# Generated by Django 5.2.9 on 2025-12-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_students_id_alter_supervisor_id'),
        ('Accounts', '0006_profile'),
    ]

    operations = [
    ]
