# Generated by Django 6.0 on 2025-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreport',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreport',
            name='supervisor_signature',
            field=models.ImageField(blank=True, null=True, upload_to='report_signatures/'),
        ),
        migrations.AlterField(
            model_name='appointmentreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('signed', 'Signed')], default='draft', max_length=20),
        ),
    ]
