# Generated by Django 6.0 on 2025-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentresponse',
            old_name='updated_at',
            new_name='responded_at',
        ),
        migrations.AddField(
            model_name='appointmentresponse',
            name='confirmed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentresponse',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
