# Generated by Django 6.0 on 2025-12-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Appointments', '0002_remove_appointment_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to='Accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_appointments', to='Accounts.supervisorprofile'),
        ),
    ]
