# Generated by Django 6.0 on 2025-12-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointments', '0002_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Academic', 'Academic'), ('Project', 'Project'), ('Consultation', 'Consultation')], max_length=50, unique=True)),
            ],
        ),
    ]
