# Generated by Django 5.2.9 on 2025-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
